name: marcas
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/resources/jsons/feed.json
    - lib/resources/jsons/comentarios.json
    - lib/resources/images/avatar.png
    - lib/resources/images/produtos.jpeg

